services:
  web:
    container_name: rest-fastapi
    build: .
    ports:
      - 5000:8000
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    container_name: fastapi-postgres
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5556:5432
    volumes:
      - fastapi_pg:/var/lib/postgresql/data

volumes:
  fastapi_pg: {}
